name: caresync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gsheets: ^0.5.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  adaptive_scrollbar: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.16.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: CareSync
  publisher_display_name: CareSync
  identity_name: caresync.app
  msix_version: 1.0.0.0
  logo_path: assets\logo.png
  capabilities: internetClient

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/min_logo.png"
    icon_size: 48 # min:48, max:256, default: 48


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700